@startuml
class Puerta {
    - ubicacion : String
    + Puerta(ubicacion : String)
    + getUbicacion() : String
}

class Casa {
    - puerta : Puerta
    + Casa(ubicacionPuerta : String)
    + asignarPuerta(ubicacion : String) : void
    + cambiarPuerta(nuevaUbicacion : String) : void
    + eliminarPuerta() : void
    + mostrarUbicacionPuerta() : void
}

Casa *-- Puerta : contiene
@enduml
